version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10.0-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: "Run Jest and Collect Coverage Reports"
          command: yarn test
      - store_artifacts:
          path: coverage
      - store_test_results:
          path: coverage
